### ISSUE TITLE
Remote decompiler service

### ISSUE THREAD

**Issue by CouleeApps** [mborgerson/mdec#17]
Some people may have computer-specific licenses of IDA / BN and are unable to run the decompilers on other machines. There should be a way to host a decompilation service on a remote machine and have the web server contact it for results.

**Comment by mborgerson** [comment]
You can do this today by installing the proprietary service package on the licensed host machine and updating the nginx config to proxy back to the service host. It's a bit of configuration work, but definitely doable.
